# Basic app config
spring.application.name=exam
server.port=8080
spring.main.allow-bean-definition-overriding=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Debug logging for Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG